### ISSUE TITLE
Any chance for uploading builds to github?

### ISSUE THREAD

**Issue by frykauf** [HackingGate/mpvx#1]

**Comment by HackingGate** [comment]
@frykauf 
Good idea.
It should available this weekend or next.
But I don't have a paid Apple Developer account (expired).
So you may need to allow the app to run from Security & Privacy menu.

**Comment by HackingGate** [comment]
Release now available.
https://github.com/HackingGate/mpvx/releases

**Comment by frykauf** [comment]
Thanks man
